### ISSUE TITLE
So the card shifted left if you could fix it

### ISSUE THREAD

**Issue by OAtulA** [OAtulA/Cards#1]
# Card shifted left

## Open to everyone

I have written some CSS in `overlay/card.html` The card moved left.
But actually, I wanted only `<p>` the texts to go left.

I have more details in the video.

Here's a video and below is the branch with the bug
[card-shifted-left-branch](https://github.com/OAtulA/Cards/tree/card-shifted-left)

https://github.com/OAtulA/Cards/assets/98654618/b6bf5116-d03c-48f3-b45d-9cc37721e6bb

**Comment by bhavaysavaliya** [comment]
@OAtulA 
Are you trying to show image left side and white side appear right?
If yes, then change angle from "var(--angle)" to "240deg".
It will look like this.
![image](https://github.com/OAtulA/Cards/assets/113259077/a5ddf629-e800-40ab-ae0b-da6f0e50e447)

**Comment by OAtulA** [comment]
No man @bhavaysavaliya 

Watch the video.

**Comment by OAtulA** [comment]
I solved it just turned the parent container to `flex-direction: column;`
